journey
    title Logitrack
    section Setup
        Bestellung: 3: Kunden
        Bestellungen finden / auflösen: 3: LOC
    section Lager
        Massenhaft labels ausdrucken: 3: LOC, Logitrack
        Palette zusammentragen: 3: LOC
        Packliste erstellen: 3: LOC, Logitrack
        Packliste label ausdrucken: 3: LOC, Logitrack
        Paletten einladen: 3: LOC, Logitrack
        Fahrzeug losschicken: 3: LOC, Logitrack
    section Veranstaltung
        Fahrzeug ausräumen: 3: LOC
        Palette als angekommen markieren: 3: LOC, Logitrack
        Paletten aufteilen: 3: LOC
        Paletten ausfahren: 3: LOC
    section Aufräumen
        Dinge zusammentragen: 3: Kunden
        Fahrten einsortieren: 3: LOC
        Sonstige nicht-logitrack dinge: 3: LOC
