CREATE TYPE operation_center AS ENUM (
    'Finanzen',
    'Backoffice',
    'Content',
    'Heralding',
    'DesignUndMotto',
    'PresseUndSocialMedia',
    'LoungeControl',
    'LoungeTechnik',
    'Infodesk',
    'Merchdesk',
    'Schilder',
    'Badges',
    'Trolle',
    'Kueche',
    'WOC',
    'Fruehstueck',
    'RaumDer1000Namen',
    'Bar',
    'Spaeti',
    'Aussenbar',
    'Kaffeebar',
    'Cocktailbar',
    'NOC',
    'POC',
    'VOC',
    'BuildupAndTeardown',
    'Infrastruktur',
    'Deko',
    'SafeR',
    'SilentHacking',
    'Projektleitung',
    'LOC'
    );

CREATE TYPE delivery_state AS ENUM (
    'Packing',
    'WaitingForTransport',
    'Transport',
    'AtGpn',
    'AtHome'
    );

create type user_authority AS ENUM (
    'MANAGE_USERS',
    'MANAGE_RESOURCES',
    'PRINT'
    );

create table if not exists logitrack_user
(
    username  varchar(255) not null
        primary key,
    enabled   boolean      not null,
    hashed_pw varchar(255) not null
);

create table if not exists logitrack_authority
(
    owning_user varchar(255) not null
        references logitrack_user,
    authority       user_authority not null,
    constraint "combination must be unique" unique (owning_user, authority)
);

create table if not exists packing_list
(
    id bigint generated by default as identity
        primary key,
    delivery_state  delivery_state not null,
    name            varchar(255) not null
);

create table if not exists euro_crate
(
    id               bigint generated by default as identity
        primary key,
    delivery_state   delivery_state not null,
    information      text,
    jira_issue       varchar(255),
    name             varchar(255) not null,
    operation_center operation_center not null,
    owning_list    bigint
            references packing_list,

    constraint "oc and name must be unique" unique (operation_center, name)
);

create index if not exists ind_euro_create_jira_issue
    on euro_crate (jira_issue);
