openapi: "3.0.4"
info:
  title: "API for the goods coordination system of the GPN LOC."
  version: "0.1.0"
servers:
  - url: "http://localhost:8080/api"
    description: "Local development server."
paths:
  /printMultiple:
    post:
      operationId: printMultipleThings
      summary: Print multiple elements into one A4 PDF
      security:
        - springCookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PrintMultipleDto"
      responses:
        200:
          description: Successfully printed
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        404:
          description: A resource didnt exist

  /users/me:
    get:
      operationId: getLoggedInUser
      summary: Gets the currently logged in user
      security:
        - springCookieAuth: []
      responses:
        200:
          description: User is logged in, here are the details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        401:
          description: user is not logged in

  /users/other/{name}:
    get:
      operationId: getSpecificUser
      summary: Get user by username
      security:
        - springCookieAuth: [ ]
      parameters:
        - name: "name"
          in: path
          required: true
          description: Username
          schema:
            type: string
            minLength: 3
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        404:
          description: User not found
        401:
          description: user is not logged in
        403:
          description: Missing permission

  /users/{username}:
    delete:
      operationId: deleteUser
      summary: Delete a user
      security:
        - springCookieAuth: [ ]
      parameters:
        - name: username
          in: path
          required: true
          description: Username
          schema:
            type: string
#            intentionally removed to prevent validation errors. shouldn't find any users to delete anyway if they're violated
#            minLength: 3
#            maxLength: 255
#            pattern: ^[a-zA-Z0-9_\-]+$
      responses:
        200:
          description: User deleted
        404:
          description: User not found
        401:
          description: Not logged in
        403:
          description: Missing permission

  /users:
    put:
      operationId: modifyUser
      summary: Modify a user
      security:
        - springCookieAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                authorities:
                  description: New authorities
                  type: array
                  items:
                    $ref: "#/components/schemas/AuthorityEnumDto"
                hashedPassword:
                  description: New BCrypt hashed password
                  maxLength: 72
                  example: $2a$10$cSa230uf6gXphAxdaFuzHuZ3nlxeCPVm1XUlwKuP1BP2BcnnkJI4S
                  type: string
                active:
                  description: New active status
                  type: boolean
                username:
                  type: string
                  minLength: 3
                  maxLength: 255
                  pattern: ^[a-zA-Z0-9_\-]+$
                  description: Username to modify
              required:
                - username
      responses:
        200:
          description: User modified
        401:
          description: Not logged in
        403:
          description: Missing permission
    post:
      operationId: createUser
      summary: Create a user
      security:
        - springCookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/UserDto"
                - type: object
                  properties:
                    hashedPassword:
                      description: BCrypt hashed password
                      maxLength: 72
                      example: $2a$10$cSa230uf6gXphAxdaFuzHuZ3nlxeCPVm1XUlwKuP1BP2BcnnkJI4S
                      type: string
                  required:
                    - hashedPassword
      responses:
        200:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        401:
          description: Not logged in
        403:
          description: Missing permission
    get:
      operationId: getUsers
      summary: Get all users
      security:
        - springCookieAuth: [ ]
      responses:
        200:
          description: User list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"

  /login:
    post:
      operationId: login
      summary: "Login and create an authenticated session."
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "301":
          description: "Successfully logged in and created a session."
          headers:
            Set-Cookie:
              schema:
                type: string
                example: JSESSIONID=abcde12345; Path=/; HttpOnly
        "400":
          description: "Provided login details do not full the specifications."
        "401":
          description: "Provided login details were not sufficient to create a new session."

components:
  securitySchemes:
    springCookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

  schemas:
    EuroCrateId:
      type: integer
      format: int64

    PrintMultipleDto:
      type: array
      items:
        type: object
        properties:
          type:
            description: Type of the print
            enum:
              - "Crate"
              - "List"
          id:
            type: integer
            format: int64
            description: Id of the resource
        required:
          - type
          - id

    LoginDto:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 255
          pattern: ^[a-zA-Z0-9_\-]+$
        password:
          type: string
      required:
        - username
        - password

    UserDto:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 255
          pattern: ^[a-zA-Z0-9_\-]+$
        authorities:
          type: array
          items:
            $ref: "#/components/schemas/AuthorityEnumDto"
        enabled:
          type: boolean
          description: Account enabled?
      required:
        - username
        - authorities
        - enabled

    AuthorityEnumDto:
      type: string
      # die müssen caps sein wegen @HasAuthority, der enum -> string converter
      # nutzt toString was den namen vom enum gibt. codegen macht die namen caps
      # -> die namen hier müssen mit den java enum namen übereinstimmen, die caps sind
      enum:
        - 'MANAGE_USERS'
        - 'MANAGE_RESOURCES'
        - 'PRINT'
